namespace CoffeeMachine.Api.Data;

/// <summary>
/// One persisted ledger row (a purchase or a cancellation).
/// Mirrors the domain <see cref="CoffeeMachine.Domain.Ledger.Transaction"/> record.
/// </summary>
public sealed class TransactionEntity
{
    /// <summary>Primary key, generated by the domain when the row is recorded.</summary>
    public Guid Id { get; set; }

    /// <summary>When the transaction was recorded (UTC).</summary>
    public DateTimeOffset Timestamp { get; set; }

    /// <summary>The machine the transaction belongs to.</summary>
    public string MachineId { get; set; } = string.Empty;

    /// <summary>Item id for purchases; empty string for cancellations.</summary>
    public string ItemId { get; set; } = string.Empty;

    /// <summary>Tendered amount for purchases; refunded amount for cancellations.</summary>
    public int PaidCents { get; set; }

    /// <summary>Change returned for purchases; 0 for cancellations.</summary>
    public int ChangeCents { get; set; }

    /// <summary>"Purchased" or "Cancelled".</summary>
    public string Status { get; set; } = string.Empty;
}

/// <summary>
/// One persisted vending machine snapshot (state, balance and both stock maps).
/// Stock maps are stored as JSON text columns keyed by denomination cents.
/// </summary>
public sealed class MachineEntity
{
    /// <summary>Primary key: the stable machine identifier.</summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>The machine state name: Idle, AwaitingSelection, Brewing or Dispensing.</summary>
    public string State { get; set; } = string.Empty;

    /// <summary>The current credit in cents.</summary>
    public int BalanceCents { get; set; }

    /// <summary>JSON map of denomination cents → coin count, e.g. {"100":23}.</summary>
    public string CoinStockJson { get; set; } = "{}";

    /// <summary>JSON map of item id → stock count, e.g. {"latte":10}.</summary>
    public string ItemStockJson { get; set; } = "{}";

    /// <summary>When the row was last written.</summary>
    public DateTimeOffset UpdatedAt { get; set; }
}
